#DO NOT USE: Docker implementation not available. Wrk2 not easily implementable
version: '3'

services:
  app:
    image: strapiosp/strapi-image
    container_name: strapi-app
    build: .
    ports:
      - 3100:3100
    volumes:
      - .:/app
