import Head from 'next/head'

export default function Home() {
  return (
    <>
      <Head>
        <title>strAPI</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo.ico" />
      </Head>
      {'Hello :)'}
    </>
  )
}
