import Head from 'next/head';
import Layout from './layout';
import styles from './home/home.module.css';
import Image from 'next/image';

export default function Home() {
  return (
    <Layout>
      <Head>
        <title>strAPI</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo.ico" />
      </Head>
      <main className={styles.homeContainer}>
        <Image
          src="/logo.png"
          alt="strAPI logo"
          height={250}
          width={250}
          className={styles.logo}
        />
        <h1 className={styles.welcomeText}>Welcome to strAPI!</h1>
        <p className={styles.stressTest}>
          Stress test your application, to destress your occupation.
        </p>
        <p className={styles.about}>
          The free and open-source stress-test app that helps you keep your API
          routes and Docker containers running efficiently, without breaking the
          bank!
        </p>
      </main>
    </Layout>
  );
}
